<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Bus Seat Booking (3+2 Layout)</title>
  <link type="text/css" rel="stylesheet" href="template.css">
  <style>
  body {
  font-family: 'Times New Roman', serif;
  background-color: #f2f2f2;
  color: #333;
  margin: 0;
  padding: 0;
}

h1 {
  font-size: 26px;
  color: #222;
  margin-top: 10px;
}

form {
  background-color: #fff;
  padding: 30px;
  max-width: 600px;
  margin: 30px auto;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0px 4px 8px rgba(0,0,0,0.1);
}

input[type="text"], select {
  width: 80%;
  padding: 8px;
  margin: 10px 0;
  font-size: 16px;
  border: 1px solid #999;
  border-radius: 4px;
}
.seat input:checked + span {
  background-color: #ffc107; /* yellow highlight */
  border-color: #ff9800;
  color: #000;
  

}


input[type="submit"] {
  background-color: #0066cc;
  color: #fff;
  padding: 12px 20px;
  border: none;
  font-size: 16px;
  border-radius: 4px;
  cursor: pointer;
  margin-top: 15px;
}

input[type="submit"]:hover {
  background-color: #004999;
}

.bus {
  margin: 20px auto;
  background-color: #fcfcfc;
  border: 1px solid #ccc;
  border-radius: 10px;
  padding: 15px;
  display: inline-block;
}

.row {
  display: flex;
  justify-content: center;
  margin-bottom: 10px;
}

.seat {
  background-color: #d4edda;
  border: 1px solid #28a745;
  color: #000;
  width: 45px;
  height: 45px;
  margin: 5px;
  border-radius: 4px;
  text-align: center;
  line-height: 45px;
  font-weight: bold;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.seat input {
  display: none;
}

.seat:hover {
  background-color:rgba(254, 229, 64, 0.73);
}

.aisle {
  width: 50px;
}

.total-price {
  font-size: 18px;
  font-weight: bold;
  margin-top: 15px;
  color: #222;
}
  </style>
</head>
<body>
<center><h1>Find Your Seat, Book Your Ride, Travel with Comfort</h1></center>


  <!-- <h1>AC Bus Seat Booking </h1> -->

  <form action="searchpro1.php" method="post" onsubmit="return validateForm()">
    <div class="bus" id="bus-layout">
    
      <!-- Seats will be generated by JavaScript -->
    </div>

    <div class="total-price">
      Selected Seats: <span id="selected-count">0</span> <br>
     Total Price: ₹<input type="text" id="total-price" name="price" readonly style="border:none; outline: none; background:none; font-weight:bold; width:80px;">

    </div>

    <br>
    Name: <input type="text" name="name" required><br><br>
    Phone: <input type="text" name="phone" maxlength="10" required><br><br>
    Gender:
    <select name="gender" required>
      <option value="">Select</option>
      <option value="male">Male</option>
      <option value="female">Female</option>
    </select><br><br>
    <input type="hidden" name="bus_id" id="bus_id" value="">


    <input type="submit" value="Book Now">
  </form>

  <script>
    var seatPrice = 450;
    var seatNumber = 1;
    const busLayout = document.getElementById('bus-layout');
    var bus_id = location.search.split('bus_id=')[1];
  
    function seatlayout(r,l)
    {
    const rowDiv = document.createElement('div');
    rowDiv.className = 'row';
      for (var i = 0; i < r; i++) {
        const label = document.createElement('label');
        label.className = 'seat';
        label.innerHTML = `<input type="checkbox" name="seats[]" value="${seatNumber}" onchange="updatePrice()"><span>${seatNumber}</span>`;
        rowDiv.appendChild(label);
        seatNumber++;
      }

      const aisle = document.createElement('div');
      aisle.className = 'aisle';
      rowDiv.appendChild(aisle);

      
      for (var i = 0; i < l; i++) {
        const label = document.createElement('label');
        label.className = 'seat';
        label.innerHTML = `<input type="checkbox" name="seats[]" value="${seatNumber}" onchange="updatePrice()"><span>${seatNumber}</span>`;
        rowDiv.appendChild(label);
        seatNumber++;
      }
       busLayout.appendChild(rowDiv);

    }

    for (let row = 0; row < 6; row++) {
      if(bus_id == 1){
       seatlayout(1,4);
         seatPrice = 700;
         
      } 
      else if(bus_id == 2){
         seatlayout(3,1);
         seatPrice = 700;
      } 
      else if(bus_id == 3){
         seatlayout(2,3);
         seatPrice = 700;
      } 
      else if(bus_id == 4){
         seatlayout(3,2);
         seatPrice = 700;
      } 
      else if(bus_id == 5){
         seatlayout(1,4);
         seatPrice = 700;
      } 
      else if(bus_id == 6){
         seatlayout(2,3);
         seatPrice = 700;
      } 
      else if(bus_id == 7){
         seatlayout(1,4);
         seatPrice = 700;
      } 

      else if(bus_id == 8){
         seatlayout(1,4);
         seatPrice = 700;
      } 

      else if(bus_id == 9){
         seatlayout(1,4);
         seatPrice = 700;
      } 

      else if(bus_id == 10){
         seatlayout(1,4);
         seatPrice = 700;
      } 

      else if(bus_id == 11){
         seatlayout(1,4);
         seatPrice = 700;
      } 

      else if(bus_id == 12){
         seatlayout(1,4);
         seatPrice = 700;
      } 

      else if(bus_id == 13){
         seatlayout(1,2);
         seatPrice = 700;
      } 

      else{
         seatlayout(2,3);
         seatPrice = 550;
      }
      
     
    }

    function updatePrice() {
      const selectedSeats = document.querySelectorAll('input[type="checkbox"]:checked');
      const count = selectedSeats.length;
      const total = count * seatPrice;
      document.getElementById('selected-count').innerText = count;
      document.getElementById('total-price').value = total;

    }

    function validateForm() {
      const selectedSeats = document.querySelectorAll('input[type="checkbox"]:checked');
      if (selectedSeats.length === 0) {
        alert("Please select at least one seat to book.");
        return false;
      }
      return true;
    }
    
  const busIdFromURL = new URLSearchParams(window.location.search).get('bus_id');
  if (busIdFromURL) {
    document.getElementById('bus_id').value = busIdFromURL;
  } else {
    alert("Bus ID is missing from URL.");
  }


  </script>

</body>
</html>

</body>
</html>